# Generated by Django 3.1 on 2021-04-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=200)),
                ('itemDesc', models.CharField(max_length=200)),
                ('itemPrice', models.IntegerField()),
            ],
        ),
    ]
