# Generated by Django 3.1 on 2021-04-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itemDesc',
            new_name='item_desc',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemName',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemPrice',
            new_name='item_price',
        ),
    ]
